### ISSUE TITLE
test workflow 报错 smtplib.SMTPServerDisconnected: Connection unexpectedly closed

### ISSUE THREAD

**Issue by weiweisss** [TideDra/zotero-arxiv-daily#12]
![image](https://github.com/user-attachments/assets/f9a8b39f-96dd-4e0a-ba36-774cc8c4fb32)

**Comment by TideDra** [comment]
你用的什么邮箱，smtp端口号是啥

**Comment by weiweisss** [comment]
> 你用的什么邮箱，smtp端口号是啥

qq邮箱，25

**Comment by TideDra** [comment]
password是smtp授权码吧，不是qq密码？

**Comment by weiweisss** [comment]
> password是smtp授权码吧，不是qq密码？

搞定了，之前是qq密码
