### ISSUE TITLE
Suggestion for Handling Various SMTP Servers Gracefully

### ISSUE THREAD

**Issue by byby221b** [TideDra/zotero-arxiv-daily#13]
Hi~ Friend, 

Thank you for developing this project—it's truly fascinating! I encountered a small issue while using a NetEase 126 email account as the sending mailbox:  

```python
smtp_server = "smtp.126.com"
smtp_port = 465
```

I tried connecting using `smtplib.SMTP_SSL(smtp_server, smtp_port)`, which worked perfectly. However, when using `smtplib.SMTP(smtp_server, smtp_port)`, I encountered an `SMTPServerDisconnected` error. After checking the source code, I noticed that only `smtp.qq.com` is handled specifically in this case.

I would suggest modifying the implementation to something like the following:

```python
try:
    server = smtplib.SMTP(smtp_server, smtp_port)
    server.starttls()
except SMTPServerDisconnected:
    server = smtplib.SMTP_SSL(smtp_server, smtp_port)
```

This approach could better handle various SMTP servers. What do you think? I'd be happy to discuss further! 😊

**Comment by TideDra** [comment]
Thanks for your suggestion! It's really a better solution. I think this is compatible for the most of mail servers!
