### ISSUE TITLE
About New paper in Monday

### ISSUE THREAD

**Issue by neverwinHao** [TideDra/zotero-arxiv-daily#16]
作者您好，昨天是周一，理论来说应该更新了文章，但是我的运行结果如下，还是没有新的文章出现
我的ARXIV_QUERY配置为：cat:cs.AI OR cat:cs.CV OR cat:cs.LG OR cat:cs.CL

![image](https://github.com/user-attachments/assets/6878b6bd-ed71-4a4b-92c9-5f3446c4d96e)

**Comment by neverwinHao** [comment]
补充：Test-Workflow完全正常，可以接收到5篇文章的邮件

**Comment by TideDra** [comment]
有时差。另外程序爬取的是前一整天（0点到24点）的论文。可以等明天再看

在 2024年12月3日，18:47，HaoLiu ***@***.***> 写道：

﻿

作者您好，昨天是周一，理论来说应该更新了文章，但是我的运行结果如下，还是没有新的文章出现
我的ARXIV_QUERY配置为：cat:cs.AI OR cat:cs.CV OR cat:cs.LG OR cat:cs.CL

image.png (view on web)<https://github.com/user-attachments/assets/6878b6bd-ed71-4a4b-92c9-5f3446c4d96e>

**Comment by TideDra** [comment]
今天依然没有收到邮件，确实有异常。检查了一下是arxiv api的问题。API索引的数据库有延迟。详见：https://groups.google.com/g/arxiv-api/c/wRqxv6Zm38Q

这确实是一个上游bug。后面会考虑直接爬网页获取最新论文。

**Comment by neverwinHao** [comment]
> 今天依然没有收到邮件，确实有异常。检查了一下是arxiv api的问题。API索引的数据库有延迟。详见：https://groups.google.com/g/arxiv-api/c/wRqxv6Zm38Q
> 
> 这确实是一个上游bug。后面会考虑直接爬网页获取最新论文。

我刚测试了一下，貌似可以了
