### ISSUE TITLE
Unable to automatically send emails?

### ISSUE THREAD

**Issue by xueboQiu** [TideDra/zotero-arxiv-daily#19]
Thank you for your amazing project, but I encountered a problem. After the configuration is completed, the test action is normal. My problem is the email will be sent automatically or do I need to run the 'main.py' file?

**Comment by TideDra** [comment]
There is a send-email-daily workflow which automatically runs everyday. If everything is ok, you should already receive today's email :)

**Comment by xueboQiu** [comment]
I have enabled this function and it works now, thank you!
