### ISSUE TITLE
Cannot retrieve new papers from arXiv API.

### ISSUE THREAD

**Issue by edsml-hz122** [TideDra/zotero-arxiv-daily#20]
<img width="1509" alt="Screenshot 2024-12-07 at 5 41 14 PM" src="https://github.com/user-attachments/assets/b98b3ad6-511b-467e-85b1-f8759ab3450a">
作者你好，我今天update了新的库重新运行了一下，虽然可以顺利运行，但是存在一个‘Cannot retrieve new papers from arXiv API.’的warning，并且也没有任何new paper，我想请问一下这个情况是正常的吗。

**Comment by TideDra** [comment]
正常的。昨天是周五，arxiv不更新。
