### ISSUE TITLE
Support for LLM API

### ISSUE THREAD

**Issue by qychen2001** [TideDra/zotero-arxiv-daily#23]
Super awesome job!
There are many LLM API services, some of which are free, such as [siliconflow](https://cloud.siliconflow.cn/i/b3XhBRAm). It would be easier to use if you could add environment variables to support API calls.
Looking forward to adding this feature!

**Comment by TideDra** [comment]
Thanks for your suggestion! I wonder what's the advantage of these services, compared with our currently used local LLM. TLDR Generation is an easy task which can be handled very well by open-source LLM. However, it consumes about 2k tokens per paper, resulting in 100k tokens consumptions everyday if MAX_PAPER_NUM=50, which is not friendly to propriatary API users. Do these free API services provide enough quota for our usage?

**Comment by qychen2001** [comment]
For [siliconflow](https://cloud.siliconflow.cn/i/b3XhBRAm), free unlimited access to state-of-the-art models such as Qwen2.5-7B-Instruct with both 1000QPM and 50,000TPM is more than enough.
In fact, I've already started the development of this feature and I think I'll PR today to implement it.

**Comment by TideDra** [comment]
Sounds great! Maybe we can set local LLM as a backup solution if API fails accidentally. Looking forward to your PR!

**Comment by qychen2001** [comment]
I opened a PR to implement this feature. Using the API will give you more speed and better performance. And when using [siliconflow](https://cloud.siliconflow.cn/i/b3XhBRAm) and Qwen/Qwen2.5-7B-Instruct, it is completely free.
