### ISSUE TITLE
MAX_PAPER_NUM failed to apply default value

### ISSUE THREAD

**Issue by inscripoem** [TideDra/zotero-arxiv-daily#28]
# Description

Test workflow run failed at stage `Run Script` with logs:

```
Using CPython 3.11.10
Creating virtual environment at: .venv
Installed 64 packages in [22](https://github.com/inscripoem/zotero-arxiv-daily/actions/runs/12328063125/job/34410792098#step:4:23)9ms
usage: main.py [-h] [--zotero_id ZOTERO_ID] [--zotero_key ZOTERO_KEY]
               [--zotero_ignore ZOTERO_IGNORE] [--max_paper_num MAX_PAPER_NUM]
               [--arxiv_query ARXIV_QUERY] [--smtp_server SMTP_SERVER]
               [--smtp_port SMTP_PORT] [--sender SENDER] [--receiver RECEIVER]
               [--password PASSWORD] [--use_llm_api USE_LLM_API]
               [--openai_api_key OPENAI_API_KEY]
               [--openai_api_base OPENAI_API_BASE] [--model_name MODEL_NAME]
               [--debug]
main.py: error: argument --max_paper_num: invalid int value: ''
Error: Process completed with exit code 2.
```

Secrets set:

- ARXIV_QUERY
- RECEIVER
- SENDER
- SENDER_PASSWORD
- SMTP_PORT
- ZOTERO_ID
- ZOTERO_KEY

# Possible Reason

I noticed that in `main.py`, the default value is set using `os.environ.get()`

https://github.com/TideDra/zotero-arxiv-daily/blob/be22cb03567de794d2697929ab9edaffdde01492/main.py#L219

The default value will only be applied when the environment variable does not exist. However, in the workflow files (both test and scheduled), the variables are created before running:

https://github.com/TideDra/zotero-arxiv-daily/blob/be22cb03567de794d2697929ab9edaffdde01492/.github/workflows/test.yml#L18-L32

So if a variable is not set by secret, `os.environ.get()` will always return `null` because the variable already exist, despite not containing anything.

BTW, I doubt this way of handling environment variables will lead to overwrite of all default values. For `OPENAI_API_KEY`, `OPENAI_API_BASE`, `MODEL_NAME` or `ZOTERO_IGNORE`, `null` is accepted for str type. For `USE_LLM_API`, I think it works fine just because its default value is `False`, and `null` is treated as `False` in a bool type.

**Comment by TideDra** [comment]
Thanks for your report! I will fix this later.
