### ISSUE TITLE
No paper update and error in arxiv api

### ISSUE THREAD

**Issue by edsml-hz122** [TideDra/zotero-arxiv-daily#30]
![image](https://github.com/user-attachments/assets/5d89a520-957c-4649-ba5a-38cb45dec30f)
作者您好 我今天发现程序在调用arxiv的api时报错了，但是通过web的似乎成功调用了，如图所示。我不能确认他是否正确调用了 因为昨天是周一 理论上会有论文更新 action的结果却显示没有新论文

**Comment by TideDra** [comment]
由于时差问题，脚本周日周一周二不更新。

**Comment by edsml-hz122** [comment]
好嘞！感谢
