### ISSUE TITLE
[Bug] LLM outputs affiliations with wrong format

### ISSUE THREAD

**Issue by hatton613** [TideDra/zotero-arxiv-daily#34]
## BUG描述
通过阅读代码发现，本项目使用LLM提取论文作者机构，但是LLM的输出可能不一定符合要求，导致输出的列表中解析比较困难，例如我使用免费的glm-4-flash的api，使用默认promt输出的作者单位被识别成数字，导致使用`affiliations = ', '.join(affiliations)`报错。
![image](https://github.com/user-attachments/assets/b4cc4b91-1252-4309-9137-250dbe30dff3)
![image](https://github.com/user-attachments/assets/b8b32fa3-cc0b-4a9f-9ded-209794b9762f)
通过将`construct_email.py`中的`affiliations = p.affiliations[:5]`修改为`affiliations = [str(a) for a in p.affiliations[:5]]`可以保证至少不会因为这个原因导致邮件发不出去。
## 其他功能建议
1. 希望把定时发送邮件的设置作为一个可设置的变量，感觉需要修改这个的人应该挺多的。
2. 希望增加语言的变量设置，例如LANG设置为zh-cn则使用中文版prompt生成机构名称和TLDR，因为本来这个项目就是希望每天快速了解下新研究，使用母语阅读会更加友好。多几个prompt选项或者通过变量自定义prompt都是很好的选择。
3. 希望在README中的ZOTERO_ID如何获取部分，多解释一句不是username，需要在API_KEY的部分复制数字ID，不然估计挺多人需要翻一下issue。
## English Version

I'm writing to express my gratitude for developing this valuable tool. However, I've encountered an issue when using the LLM to extract author affiliations.

Specifically, I've noticed that the free glm-4-flash API, when used with the default prompt, often identifies author affiliations as numbers, resulting in errors when trying to join them into a string using `affiliations = ', '.join(affiliations)`. I was able to temporarily resolve this by modifying `construct_email.py` to convert affiliations to strings using `affiliations = [str(a) for a in p.affiliations[:5]]`.

**Feature requests:**
1. **Configurable email scheduling:** I suggest making the email sending interval a configurable variable, as this is likely to be a common customization.
2. **Language support:** It would be beneficial to add a language variable, such as `LANG`, allowing users to specify a language (e.g., `zh-cn` for Chinese) and use the corresponding prompt to generate affiliation names and TL;DRs. This would enhance the user experience, especially for those wanting to quickly grasp new research in their native language. Multiple prompts or a custom prompt variable could be implemented.
3. **Zotero ID clarification:** The README should states that ZOTERO_ID is not the username. To avoid confusion, it would be helpful to explicitly mention that the numerical ID should be copied from the API key section.

Thank you again for your hard work on this project. I hope these suggestions can help improve it further.

**Comment by TideDra** [comment]
感谢你的建议！格式错误的bug后续会修复。不过API建议使用siliconflow的Qwen2.5-7b-instruct，它绝大多数情况下输出的格式是正确的。

**Comment by TideDra** [comment]
邮件发送的时间即workflow运行的时间，这个需要手动修改workflow文件，即`.github/workflow/main.yml`，无法通过环境变量设置

**Comment by hatton613** [comment]
谢谢你的回复！🙏
