### ISSUE TITLE
Rendering emails takes long time and leads to cancellation

### ISSUE THREAD

**Issue by Breeze2003** [TideDra/zotero-arxiv-daily#40]
![IMG_0057](https://github.com/user-attachments/assets/4f651750-5f2f-4918-b0ba-baf000853460)

Why was it so slow? All the jobs failed because of this slow rendering. 

Thank you so much!

**Comment by TideDra** [comment]
#42 has fixed this problem. It takes 100s per paper averagely and should be within the 6h workflow quota, given 100 papers. I suggest to use the free LLM API mentioned in the README, which has much faster and better performance. You can also set a smaller MAX_PAPER_NUM. The default 100 is redundant for most people.
