### ISSUE TITLE
No new paper found

### ISSUE THREAD

**Issue by neverwinHao** [TideDra/zotero-arxiv-daily#5]
作者您好，请问下面这种情况是怎么回事呢？
是SENDER配置有问题吗？SENDER是不是随便一个能用的qq邮箱就可以呢？
![image](https://github.com/user-attachments/assets/57f3759d-21f9-40e3-975a-7378c505c12b)
感谢您的回复！

**Comment by neverwinHao** [comment]
> 作者您好，请问下面这种情况是怎么回事呢？ 是SENDER配置有问题吗？SENDER是不是随便一个能用的qq邮箱就可以呢？ ![image](https://private-user-images.githubusercontent.com/106739665/390985707-57f3759d-21f9-40e3-975a-7378c505c12b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjI1ODAsIm5iZiI6MTczMjg2MjI4MCwicGF0aCI6Ii8xMDY3Mzk2NjUvMzkwOTg1NzA3LTU3ZjM3NTlkLTIxZjktNDBlMy05NzVhLTczNzhjNTA1YzEyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwNjM4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzM5NzM4OWJmZmRhNDBmMGNhNjY3MjQ1MGZmZThhZWU4NWJmM2VlZjg0N2FkOWE3MWVlZThiYjYzNGYwNzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ENvUdthvhZjaGcw8s8BSRFOGGHeGVKNm9SU3mcTy0y0) 感谢您的回复！
 #3中大家好像也遇到了相似的问题

**Comment by TideDra** [comment]
与邮箱无关。可能是因为arxiv正在放假。可以扩大搜索范围来继续测试。详见 #3

**Comment by weiweisss** [comment]
现在也是 no new papers found，可能是哪配置有问题吗？

**Comment by weiweisss** [comment]
> 与邮箱无关。可能是因为arxiv正在放假。可以扩大搜索范围来继续测试。详见 #3

现在也是 no new papers found，可能是哪配置有问题吗？
