### ISSUE TITLE
About Test-Workflow

### ISSUE THREAD

**Issue by neverwinHao** [TideDra/zotero-arxiv-daily#8]
您好，测试新的TestWork flow的时候会出现下面的bug，看起来arxiv中的五篇论文已经获取了？
![image](https://github.com/user-attachments/assets/0ba963cd-7969-42f9-b8dd-af741bd61d5f)

**Comment by TideDra** [comment]
第20行显示没能获取到zotero paper哦，检查一下zotero配置是否正确

**Comment by neverwinHao** [comment]
> 第20行显示没能获取到zotero paper哦，检查一下zotero配置是否正确

我看key好像被调用了，其他参数似乎都是收发过程需要的，请问这是怎么回事呢
![image](https://github.com/user-attachments/assets/6ef20dde-a2e2-4baa-afe1-806a89ed552c)

**Comment by TideDra** [comment]
你的zotero中都含有哪些类型的文献呢，默认是只爬取conferencePaper， JournalArtical和Preprint

**Comment by neverwinHao** [comment]
有Conference paper和Preprint


---- Replied Message ----
| From | ***@***.***> |
| Date | 11/29/2024 17:26 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [TideDra/zotero-arxiv-daily] About Test-Workflow (Issue #8) |

你的zotero中都含有哪些类型的文献呢，默认是只爬取conferencePaper， JournalArtical和Preprint

**Comment by TideDra** [comment]
摘要(abstract)这一项都不为空吗

**Comment by neverwinHao** [comment]
刚刚检查了下，都不为空


---- Replied Message ----
| From | ***@***.***> |
| Date | 11/29/2024 17:30 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [TideDra/zotero-arxiv-daily] About Test-Workflow (Issue #8) |

摘要(abstract)这一项都不为空吗

**Comment by TideDra** [comment]
你访问的是zotero个人文献库还是群组文献库呢

**Comment by neverwinHao** [comment]
是个人的


---- Replied Message ----
| From | ***@***.***> |
| Date | 11/29/2024 17:32 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [TideDra/zotero-arxiv-daily] About Test-Workflow (Issue #8) |

你访问的是zotero个人文献库还是群组文献库呢

**Comment by neverwinHao** [comment]
> 你访问的是zotero个人文献库还是群组文献库呢

您好，问题解决了，文献库的Date字段也不能为空

**Comment by neverwinHao** [comment]
> 你访问的是zotero个人文献库还是群组文献库呢

感谢您的回复！

**Comment by stevenzhang9577** [comment]
请问每篇论文是必须要有 abstract 吗，库里总共有 4700 篇论文，但只检测出 38 篇
<img width="1310" alt="image" src="https://github.com/user-attachments/assets/8f4c5d4a-2a8b-43a6-86b4-b49a0f2ab1f1">

**Comment by neverwinHao** [comment]
> 请问每篇论文是必须要有 abstract 吗，库里总共有 4700 篇论文，但只检测出 38 篇 <img alt="image" width="1310" src="https://private-user-images.githubusercontent.com/30944668/391550688-8f4c5d4a-2a8b-43a6-86b4-b49a0f2ab1f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDQ0NDYsIm5iZiI6MTczMzE0NDE0NiwicGF0aCI6Ii8zMDk0NDY2OC8zOTE1NTA2ODgtOGY0YzVkNGEtMmE4Yi00M2E2LTg2YjQtYjQ5YTBmMmFiMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDEyNTU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNWEzNmM1MmY0ZjU5ZWNjMDJkNTYyYzNjOTNkMThmMWEwM2MxNWE0OWFlOGNiMGIwNTQ3NDU3YjVlZmRkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x9Irj9ic70dEgPUs-A8qeeyKUZMYN7XGEapC8aQvo3w">

我感觉应该是的

**Comment by TideDra** [comment]
> 请问每篇论文是必须要有 abstract 吗，库里总共有 4700 篇论文，但只检测出 38 篇 <img alt="image" width="1310" src="https://private-user-images.githubusercontent.com/30944668/391550688-8f4c5d4a-2a8b-43a6-86b4-b49a0f2ab1f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDQ3ODMsIm5iZiI6MTczMzE0NDQ4MywicGF0aCI6Ii8zMDk0NDY2OC8zOTE1NTA2ODgtOGY0YzVkNGEtMmE4Yi00M2E2LTg2YjQtYjQ5YTBmMmFiMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDEzMDEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNThlZDRmZmI1N2U2ODJjZGI2NmJjZDcxYzQyNTMzZTI5NzcxY2U2ZGE4ZTEwZmVmNWUxMmM5YjI5ZWE5NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FigtqCgLJ0sVVDQTwKVdjZb8Elmcaw3cjxCH5646qPE">

是的，因为目前是以论文abstract作为论文特征。想问下没有abstract的论文是什么类型的？zotero理论上是可以提取绝大多数论文的元数据，生成abstract的。如果有特殊情况可以另开一个issue讨论哈

**Comment by stevenzhang9577** [comment]
> > 请问每篇论文是必须要有 abstract 吗，库里总共有 4700 篇论文，但只检测出 38 篇 <img alt="image" width="1310" src="https://private-user-images.githubusercontent.com/30944668/391550688-8f4c5d4a-2a8b-43a6-86b4-b49a0f2ab1f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDQ3ODMsIm5iZiI6MTczMzE0NDQ4MywicGF0aCI6Ii8zMDk0NDY2OC8zOTE1NTA2ODgtOGY0YzVkNGEtMmE4Yi00M2E2LTg2YjQtYjQ5YTBmMmFiMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDEzMDEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNThlZDRmZmI1N2U2ODJjZGI2NmJjZDcxYzQyNTMzZTI5NzcxY2U2ZGE4ZTEwZmVmNWUxMmM5YjI5ZWE5NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FigtqCgLJ0sVVDQTwKVdjZb8Elmcaw3cjxCH5646qPE">
> 
> 是的，因为目前是以论文abstract作为论文特征。想问下没有abstract的论文是什么类型的？zotero理论上是可以提取绝大多数论文的元数据，生成abstract的。如果有特殊情况可以另开一个issue讨论哈

有一些是直接从 github 复制的引用 bib 文件，有的是因为之前空间占用问题用"Del Item With Attachment"插件清理了 Abstract，请问不忙时方便写个用 Google scholar或本地 pdf 直接检索填写 abstract 的插件吗？[相关论坛链接](https://forums.zotero.org/discussion/102925/plugin-to-fetch-missing-abstracts)

**Comment by TideDra** [comment]
> > > 请问每篇论文是必须要有 abstract 吗，库里总共有 4700 篇论文，但只检测出 38 篇 <img alt="image" width="1310" src="https://private-user-images.githubusercontent.com/30944668/391550688-8f4c5d4a-2a8b-43a6-86b4-b49a0f2ab1f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDQ3ODMsIm5iZiI6MTczMzE0NDQ4MywicGF0aCI6Ii8zMDk0NDY2OC8zOTE1NTA2ODgtOGY0YzVkNGEtMmE4Yi00M2E2LTg2YjQtYjQ5YTBmMmFiMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDEzMDEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNThlZDRmZmI1N2U2ODJjZGI2NmJjZDcxYzQyNTMzZTI5NzcxY2U2ZGE4ZTEwZmVmNWUxMmM5YjI5ZWE5NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FigtqCgLJ0sVVDQTwKVdjZb8Elmcaw3cjxCH5646qPE">
> > 
> > 
> > 是的，因为目前是以论文abstract作为论文特征。想问下没有abstract的论文是什么类型的？zotero理论上是可以提取绝大多数论文的元数据，生成abstract的。如果有特殊情况可以另开一个issue讨论哈
> 
> 有一些是直接从 github 复制的引用 bib 文件，有的是因为之前空间占用问题用"Del Item With Attachment"插件清理了 Abstract，请问不忙时方便写个用 Google scholar或本地 pdf 直接检索填写 abstract 的插件吗？[相关论坛链接](https://forums.zotero.org/discussion/102925/plugin-to-fetch-missing-abstracts)

不管怎样，首先要保证item的类型是conferencePaper、preprint、journalPaper之一。其次，item的DOI、仓库ID、标题，至少有一个不为空，这样才能准确定位论文。满足这两个条件的话，理论上可以用semantic scholar获取abstract。后续会考虑更新自动抓取abstract的功能

**Comment by TideDra** [comment]
> > > 请问每篇论文是必须要有 abstract 吗，库里总共有 4700 篇论文，但只检测出 38 篇 <img alt="image" width="1310" src="https://private-user-images.githubusercontent.com/30944668/391550688-8f4c5d4a-2a8b-43a6-86b4-b49a0f2ab1f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDQ3ODMsIm5iZiI6MTczMzE0NDQ4MywicGF0aCI6Ii8zMDk0NDY2OC8zOTE1NTA2ODgtOGY0YzVkNGEtMmE4Yi00M2E2LTg2YjQtYjQ5YTBmMmFiMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDEzMDEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNThlZDRmZmI1N2U2ODJjZGI2NmJjZDcxYzQyNTMzZTI5NzcxY2U2ZGE4ZTEwZmVmNWUxMmM5YjI5ZWE5NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FigtqCgLJ0sVVDQTwKVdjZb8Elmcaw3cjxCH5646qPE">
> > 
> > 
> > 是的，因为目前是以论文abstract作为论文特征。想问下没有abstract的论文是什么类型的？zotero理论上是可以提取绝大多数论文的元数据，生成abstract的。如果有特殊情况可以另开一个issue讨论哈
> 
> 有一些是直接从 github 复制的引用 bib 文件，有的是因为之前空间占用问题用"Del Item With Attachment"插件清理了 Abstract，请问不忙时方便写个用 Google scholar或本地 pdf 直接检索填写 abstract 的插件吗？[相关论坛链接](https://forums.zotero.org/discussion/102925/plugin-to-fetch-missing-abstracts)

可以看一下这个action插件，看起来已经实现了你说的这个功能，https://github.com/windingwind/zotero-actions-tags/discussions/182

**Comment by stevenzhang9577** [comment]
或者说是否有可能将 extra 区域的 TLDR 加进去，这个是有现成插件可以生成

**Comment by TideDra** [comment]
> 或者说是否有可能将 extra 区域的 TLDR 加进去，这个是有现成插件可以生成

不能保证所有用户的extra字段都是TLDR。不过你可以修改你自己仓库的代码实现这一功能。

**Comment by zyushun** [comment]
你好，我也遇到了类似的问题，请问该怎么解决呢？翻了下这个issue但没太看懂..

<img width="1351" alt="image" src="https://github.com/user-attachments/assets/18518f76-1dab-4a32-a276-688b92dc8cf9" />

RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x384 and ***x1)

**Comment by TideDra** [comment]
> 你好，我也遇到了类似的问题，请问该怎么解决呢？翻了下这个issue但没太看懂..
> 
> 
> 
> <img width="1351" alt="image" src="https://github.com/user-attachments/assets/18518f76-1dab-4a32-a276-688b92dc8cf9" />
> 
> 
> 
> RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x384 and ***x1)

zotero配置不对，再好好看看README

**Comment by ZixianGao** [comment]
#

> > 你访问的是zotero个人文献库还是群组文献库呢
> 
> 您好，问题解决了，文献库的Date字段也不能为空

 请问这个是在哪里设置？
